name: Compiler Tests

on:
  push:
    paths: ['src/**.fu', '.github/workflows/compiler_tests.yml']
  pull_request:
    paths: ['src/**.fu', '.github/workflows/compiler_tests.yml']
    types: [opened, synchronize]

jobs:
  ubuntu-gcc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Rivet compiler
        run: |
          wget https://github.com/fusionlanguage/fut/releases/download/fut-3.2.7/fut_3.2.7-1_amd64.deb
          sudo dpkg -i fut_3.2.7-1_amd64.deb
          sudo apt install libgtk-4-dev
          make
          ./ric -h
