name: Compiler Tests

on:
  push:
    branches:
      - 'main'
    paths: ['lib/**.ri', 'ric/**.py', 'tests/**']
  pull_request:
    paths: ['lib/**.ri', 'ric/**.py', 'tests/**']
    types: [opened, synchronize]

jobs:
  ubuntu-clang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build V
        run: |
          git clone https://github.com/vlang/v
          cd v && make
          sudo ./v symlink
          cd ..

      - name: Build Rivet Compiler
        run: |
          v ric && ./ric
