name: Compiler Tests

on:
  push:
    paths: ['src/**.v', '.github/workflows/compiler_tests.yml']
  pull_request:
    paths: ['src/**.v', '.github/workflows/compiler_tests.yml']
    types: [opened, synchronize]

jobs:
  ubuntu-gcc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Rivet compiler
        run: |
          git clone https://github.com/vlang/v
          cd v && make && sudo ./v symlink
          cd ..
          v test compiler
          v tests/run_tests.vsh
