name: Test compiler

on:
  push:
    paths: ['rivetc/**.py']
    branches: [main]

jobs:
  test-compiler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Rivet source code
        uses: actions/checkout@v2

      - name: Run compiler
        run: |
          python3 ./rivetc.py src/tests/grammar.ri
