name: Compiler Tests

on:
  push:
    paths: ['cmd/**.v', 'compiler/**.v', '.github/workflows/compiler_tests.yml', 'tests/**']
  pull_request:
    paths: ['cmd/**.v', 'compiler/**.v', '.github/workflows/compiler_tests.yml', 'tests/**']
    types: [opened, synchronize]

jobs:
  ubuntu-gcc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build V
        run: |
          git clone https://github.com/vlang/v
          cd v && make && sudo ./v symlink
          cd ..

      - name: Build Rivet compiler
        run: |
          v -o rivetc cmd/

      - name: Run Rivet compiler tests
        run: |
          v test compiler
          v tests/run_tests.vsh
