name: Test compiler

on:
  push:
    paths: ['rivetc/**.py']
    branches: [main]

jobs:
  build-compiler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Rivet source code
        uses: actions/checkout@v2

      - name: Install Pip & Lark & llvmlite
        run: |
          sudo apt-get install python3-pip
          sudo pip install lark llvmlite

      - name: Run compiler
        run: |
          python3 ./rivetc.py rivetc/test_grammar.ri
