name: Library Tests

on:
  push:
    paths: ['lib/**.ri', 'rivetc/**.py']
    branches: [main]
  pull_request:
    paths: ['lib/**.ri', 'rivetc/**.py']
    types: [opened, synchronize]

jobs:
  ubuntu-clang:
    runs-on: ubuntu-latest
    env:
      RIVET_CC_TEST: clang
    steps:
      - uses: actions/checkout@v2

      - name: Run runtime tests
        run: |
          python3 rivetc --backend-compiler clang -t lib/runtime/tests/

      - name: Run standard library tests
        run: |
          python3 rivetc --backend-compiler clang -t lib/std/tests/

  ubuntu-gcc:
    runs-on: ubuntu-latest
    env:
      RIVET_CC_TEST: gcc
    steps:
      - uses: actions/checkout@v2

      - name: Run runtime tests
        run: |
          python3 rivetc -t lib/runtime/tests/

      - name: Run standard library tests
        run: |
          python3 rivetc -t lib/std/tests/
