name: Library Tests

on:
  push:
    paths: ['lib/**.ri', 'rivetc/**.py']
    branches: [main]
  pull_request:
    paths: ['lib/**.ri', 'rivetc/**.py']
    types: [opened, synchronize]

jobs:
  ubuntu-clang:
    runs-on: ubuntu-latest
    env:
      RIVET_CC_TEST: clang
    steps:
      - uses: actions/checkout@v3

      - name: Run core library tests
        run: |
          python3 rivetc -bc clang -t lib/core/tests/

      - name: Run standard library tests
        run: |
          python3 rivetc -bc clang -t lib/std/tests/

      - name: Run Rivet self-hosted tests
        run: |
          python3 rivetc -bc clang -t lib/rivet/tests/

  ubuntu-gcc:
    runs-on: ubuntu-latest
    env:
      RIVET_CC_TEST: gcc
    steps:
      - uses: actions/checkout@v3

      - name: Run core library tests
        run: |
          python3 rivetc -t lib/core/tests/

      - name: Run standard library tests
        run: |
          python3 rivetc -t lib/std/tests/

      - name: Run Rivet self-hosted tests
        run: |
          python3 rivetc -t lib/rivet/tests/
