name: Self-hosted Compiler - Nightly Build

on:
  push:
    branches:
      - main
    paths: ['lib/**.ri', 'rivetc/**.py', 'cmd/**.ri']

jobs:
  ubuntu-gcc:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Compile the self-hosted compiler
        run: |
          python3 rivetc -o rivet cmd/
          ./rivet version
          mkdir rivet-nightly-linux-amd64
          # Copy binary
          cp rivet rivet-nightly-linux-amd64/
          # Copy LICENSE
          cp LICENSE rivet-nightly-linux-amd64/
          # Copy library
          cp -r lib/ rivet-nightly-linux-amd64/
          # Download latest docs
          git clone https://github.com/rivet-lang/docs -b gh-pages --depth=1
          # Copy docs
          cp -r docs/ rivet-nightly-linux-amd64/
          zip -r rivet-nightly-linux-amd64.zip rivet-nightly-linux-amd64/

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "nightly"
          prerelease: true
          title: "Self-hosted Compiler - Nightly Build"
          files: rivet-nightly-linux-amd64.zip
